[caddy-login-401]
enabled = true
filter = caddy-login-401
logpath = /var/log/caddy/access.log
backend = polling

maxretry = 5
findtime = 600
bantime  = 3600

banaction = nftables-multiport
port = http,https
